steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/gcp-training-710/gcf-artifacts/flask_app-nm', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/gcp-training-710/gcf-artifacts/flask_app-nm']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'hospitalmanagement-nm'
  - '--image'
  - 'us-central1-docker.pkg.dev/gcp-training-710/gcf-artifacts/flask_app-nm'
  - '--port'
  - '8080'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--max-instances'
  - '5'
  - '--timeout'
  - '3600'
  - '--memory'
  - '1024Mi'
  

images:
- us-central1-docker.pkg.dev/gcp-training-710/gcf-artifacts/flask_app-nm

options:
  logging: CLOUD_LOGGING_ONLY


